### ISSUE TITLE
Updating playing? variable

### ISSUE THREAD

**Issue by irosenb** [sunny/so-nice#11]
This isn't so much of an actual issue as something I'm trying to do. You probably remember me from committing to the anyplayer gem. Now I'm trying to incorporate that playing? boolean into so-nice, but I'm noticing that when I pause the music, my assigned variable @playing does not recognize that. How can I update the variable each time, just as the song info updates every time the song changes?

``` ruby
get '/' do
  @title = $player.track
  @artist = $player.artist
  @album = $player.album
  if $player.name == "iTunes" or $player.name == "Spotify Mac"
    @playing = $player.playing? # How can this be updated each time I pause/play the music? 
  end
```

**Comment by sunny** [comment]
Closing this for now. Let me know if you're still fiddling with it and we can reopen.
