### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by sticilface** [sunny/so-nice#24]
Running iTunes 12.0.1.26
Windows 7
Ruby 1.9.3 with dev kit

installed sonice, and the first time it ran I got the webpage and controls, and some names of some songs came up and then it stopped working.  Not sure if it ever managed to control iTunes at all.

On future attempts to get it to work I get the internal server error and nothing comes up.  
Here is the output from the cmd line.

C:\Ruby193\devkit>sonice
== Sinatra/1.4.5 has taken the stage on 3000 for production with backup from Thi
n
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop
Looking for a player...
Connected to iTunes Windows
NoMethodError - undefined method `name' for nil:NilClass:
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/anyplayer-1.1.4/lib/anyplayer/player
s/itunes_windows.rb:43:in`track'
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/sonice-2.1.2/lib/sonice/app.rb:44:in
 `block in <class:App>'
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:16
03:in`call'
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:16
03:in `block in compile!'
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:96
6:in`[]'
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:96
6:in `block (3 levels) in route!'
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:98
5:in`route_eval'
        C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:96

**Comment by sunny** [comment]
I'll close the issue since it's very old. Let me know if the issue still occurs, and we can have a new look at it.
