### ISSUE TITLE
Display filename if no tags

### ISSUE THREAD

**Issue by nagualcode** [sunny/so-nice#26]
I have many untagged flac files in my collection, and I would be so nice if I could display the filename, with some random background images (like chromecast or bing images).
Thank you for this well done project.

**Comment by sunny** [comment]
Hey @nagualcode! Sorry for not responding earlier. Are you still interested in that feature? Perhaps the way to fix that would be for [anyplayer](https://github.com/sunny/anyplayer) to fallback to the filename when the track is unnamed.

**Comment by sunny** [comment]
@nagualcode If you are still using so-nice, what music player are you using it with?

**Comment by nagualcode** [comment]
Hi Sunny, Music Player Daemon (MPD).

**Comment by sunny** [comment]
MPD now falls back to the file name if the title was not found. Added in sunny/anyplayer#17 and a new version of sonice has been released: 2.2.0 🎉

Enjoy!

**Comment by nagualcode** [comment]
That is great!
