### ISSUE TITLE
New favicon

### ISSUE THREAD

**Issue by sunny** [sunny/so-nice#43]
On dark screens especially, the favicon is kinda messy.

![image](https://user-images.githubusercontent.com/132/94117209-3f3aa900-fe4c-11ea-9788-9e7cb15bc1b7.png)

**Comment by TheMimiCodes** [comment]
Hello! I'm currently doing the Hacktoberfest 2020 challenge and would like to help by improving the favicon.

Would you like to keep the current favicon for light backgrounds and have a new inverted version that shows up correctly on dark backgrounds? Or rather have a completely new favicon that works well on both light and dark backgrounds?

**Comment by sunny** [comment]
Hey @TheMimiCodes! Ideally one that works well for both, as it's less code to maintain. But having two separate icons can be a solution if needed!

I don’t even recall where the original icon comes from I’m afraid, so feel free to go where your heart takes you :)

**Comment by sunny** [comment]
(`hacktoberfest` topic added to the repo ✅)

**Comment by TheMimiCodes** [comment]
I opened a PR for this. Thank you!
