### ISSUE TITLE
sonice's executable "rake" conflicts with anyplayer

### ISSUE THREAD

**Issue by Saroumane** [sunny/so-nice#53]
I get this message when installing on Ubuntu 20.10, Ruby 2.7

```
$ sudo gem install sonice
Fetching tilt-2.0.10.gem
Fetching ruby-mpd-0.3.3.gem
Fetching anyplayer-1.2.0.gem
Fetching rack-2.2.3.gem
Fetching sinatra-2.1.0.gem
Fetching rack-protection-2.1.0.gem
Fetching ruby2_keywords-0.0.2.gem
Fetching mustermann-1.1.1.gem
Fetching sonice-2.2.0.gem
Fetching xml-simple-1.1.7.gem
Successfully installed ruby-mpd-0.3.3
Successfully installed anyplayer-1.2.0
Successfully installed rack-2.2.3
Successfully installed tilt-2.0.10
Successfully installed rack-protection-2.1.0
Successfully installed ruby2_keywords-0.0.2
Successfully installed mustermann-1.1.1
Successfully installed sinatra-2.1.0
Successfully installed xml-simple-1.1.7
sonice's executable "rake" conflicts with anyplayer
Overwrite the executable? [yN]  
```
I chose "yes",
and then the installation is stalled :

```
Overwrite the executable? [yN]  y
Successfully installed sonice-2.2.0
Parsing documentation for ruby-mpd-0.3.3
Installing ri documentation for ruby-mpd-0.3.3
Parsing documentation for anyplayer-1.2.0
Installing ri documentation for anyplayer-1.2.0
Parsing documentation for rack-2.2.3
Installing ri documentation for rack-2.2.3
Parsing documentation for tilt-2.0.10
Installing ri documentation for tilt-2.0.10
Parsing documentation for rack-protection-2.1.0
Installing ri documentation for rack-protection-2.1.0
Parsing documentation for ruby2_keywords-0.0.2
Installing ri documentation for ruby2_keywords-0.0.2
Parsing documentation for mustermann-1.1.1
Installing ri documentation for mustermann-1.1.1
Parsing documentation for sinatra-2.1.0
Installing ri documentation for sinatra-2.1.0
```
Nevermind, I relaunched `sudo gem install sonice` and installation ends without error the 2nd time.
I still don't know if I should have allowed "rake" overwriting "anyplayer".

It works amazingly well, even if I don't understand the "voting system", and the artist picture is missing. Hope this fix ( https://github.com/sunny/so-nice/pull/49 ) will be merged soon !

**Comment by sunny** [comment]
Thank you for bringing this up! That's an error, `rake` should not be packaged inside `anyplayer` or `sonice`.

**Comment by sunny** [comment]
Version 2.2.1 was released to fix this 🎉 

> even if I don't understand the "voting system"

Yeah, it's not very explicit, but it's a way to skip a song after several people decided to vote against it. You should disable it if it’s not useful to you.

> and the artist picture is missing

Yes, unfortunately last.fm’s API doesn’t provide the photos anymore. Hopefully that PR gets merged soon.

Thank you for feedback, @Saroumane :)

**Comment by Saroumane** [comment]
> Yeah, it's not very explicit, but it's a way to skip a song after several people decided to vote against it. You should disable it if it’s not useful to you.

Yes, I get it but when/how the skip decision is handled ? I guess web clients can cast their vote anytime, but even after reading the code I don't understand if there is a threshold value that triggers the skip. (No offense, your code is probably well presented but I never used Ruby :) 

Use case : 2 sonice web client connected. Can it be configured so that the current song is skipped as soon as 2 "skip votes" are casted ?

**Comment by sunny** [comment]
Yes, there's a threshold of 5. No offense taken, the threshold is [a constant inside anyplayer](https://github.com/sunny/anyplayer/blob/main/lib/anyplayer/player.rb#L19)… so really not ideal.

This is definitely something that could use some configuration, e.g. `SONICE_VOTING_SKIP_AFTER=2`.
